{
    "name": "Field Diff Tracking",
    "version": "17.0.1.0.0",
    "summary": "Track diffs for text, char, and HTML fields",
    "sequence": 0,
    "description": """The Field Diff Tracking module provides a mixin for Odoo models to track and display differences in text, char, and HTML fields. This module enhances Odoo's native change tracking by providing a more detailed and visually appealing diff view in the chatter.""",
    "category": "Technical",
    "author": "Harrison Consulting, LLC",
    "website": "https://www.harrison.consulting",
    "license": "LGPL-3",
    "depends": ["base", "mail"],
    "data": [],
    "installable": True,
    "application": False,
    "auto_install": False,
}
